/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MaintenanceRecord } from "./MaintenanceRecord";
import { MaintenanceRecordCountArgs } from "./MaintenanceRecordCountArgs";
import { MaintenanceRecordFindManyArgs } from "./MaintenanceRecordFindManyArgs";
import { MaintenanceRecordFindUniqueArgs } from "./MaintenanceRecordFindUniqueArgs";
import { CreateMaintenanceRecordArgs } from "./CreateMaintenanceRecordArgs";
import { UpdateMaintenanceRecordArgs } from "./UpdateMaintenanceRecordArgs";
import { DeleteMaintenanceRecordArgs } from "./DeleteMaintenanceRecordArgs";
import { Flight } from "../../flight/base/Flight";
import { MaintenanceRecordService } from "../maintenanceRecord.service";
@graphql.Resolver(() => MaintenanceRecord)
export class MaintenanceRecordResolverBase {
  constructor(protected readonly service: MaintenanceRecordService) {}

  async _maintenanceRecordsMeta(
    @graphql.Args() args: MaintenanceRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MaintenanceRecord])
  async maintenanceRecords(
    @graphql.Args() args: MaintenanceRecordFindManyArgs
  ): Promise<MaintenanceRecord[]> {
    return this.service.maintenanceRecords(args);
  }

  @graphql.Query(() => MaintenanceRecord, { nullable: true })
  async maintenanceRecord(
    @graphql.Args() args: MaintenanceRecordFindUniqueArgs
  ): Promise<MaintenanceRecord | null> {
    const result = await this.service.maintenanceRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MaintenanceRecord)
  async createMaintenanceRecord(
    @graphql.Args() args: CreateMaintenanceRecordArgs
  ): Promise<MaintenanceRecord> {
    return await this.service.createMaintenanceRecord({
      ...args,
      data: {
        ...args.data,

        flight: args.data.flight
          ? {
              connect: args.data.flight,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => MaintenanceRecord)
  async updateMaintenanceRecord(
    @graphql.Args() args: UpdateMaintenanceRecordArgs
  ): Promise<MaintenanceRecord | null> {
    try {
      return await this.service.updateMaintenanceRecord({
        ...args,
        data: {
          ...args.data,

          flight: args.data.flight
            ? {
                connect: args.data.flight,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MaintenanceRecord)
  async deleteMaintenanceRecord(
    @graphql.Args() args: DeleteMaintenanceRecordArgs
  ): Promise<MaintenanceRecord | null> {
    try {
      return await this.service.deleteMaintenanceRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Flight, {
    nullable: true,
    name: "flight",
  })
  async getFlight(
    @graphql.Parent() parent: MaintenanceRecord
  ): Promise<Flight | null> {
    const result = await this.service.getFlight(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
