/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlightService } from "../flight.service";
import { FlightCreateInput } from "./FlightCreateInput";
import { Flight } from "./Flight";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightWhereUniqueInput } from "./FlightWhereUniqueInput";
import { FlightUpdateInput } from "./FlightUpdateInput";
import { MaintenanceRecordFindManyArgs } from "../../maintenanceRecord/base/MaintenanceRecordFindManyArgs";
import { MaintenanceRecord } from "../../maintenanceRecord/base/MaintenanceRecord";
import { MaintenanceRecordWhereUniqueInput } from "../../maintenanceRecord/base/MaintenanceRecordWhereUniqueInput";

export class FlightControllerBase {
  constructor(protected readonly service: FlightService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flight })
  async createFlight(@common.Body() data: FlightCreateInput): Promise<Flight> {
    return await this.service.createFlight({
      data: data,
      select: {
        approvalComments: true,
        approvalStatus: true,
        approveStatus: true,
        arrivalAirport: true,
        arrivalTime: true,
        associatedPilot: true,
        createdAt: true,
        departureAirport: true,
        departureTime: true,
        flightNumber: true,
        id: true,
        remark: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Flight] })
  @ApiNestedQuery(FlightFindManyArgs)
  async flights(@common.Req() request: Request): Promise<Flight[]> {
    const args = plainToClass(FlightFindManyArgs, request.query);
    return this.service.flights({
      ...args,
      select: {
        approvalComments: true,
        approvalStatus: true,
        approveStatus: true,
        arrivalAirport: true,
        arrivalTime: true,
        associatedPilot: true,
        createdAt: true,
        departureAirport: true,
        departureTime: true,
        flightNumber: true,
        id: true,
        remark: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    const result = await this.service.flight({
      where: params,
      select: {
        approvalComments: true,
        approvalStatus: true,
        approveStatus: true,
        arrivalAirport: true,
        arrivalTime: true,
        associatedPilot: true,
        createdAt: true,
        departureAirport: true,
        departureTime: true,
        flightNumber: true,
        id: true,
        remark: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlight(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() data: FlightUpdateInput
  ): Promise<Flight | null> {
    try {
      return await this.service.updateFlight({
        where: params,
        data: data,
        select: {
          approvalComments: true,
          approvalStatus: true,
          approveStatus: true,
          arrivalAirport: true,
          arrivalTime: true,
          associatedPilot: true,
          createdAt: true,
          departureAirport: true,
          departureTime: true,
          flightNumber: true,
          id: true,
          remark: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flight })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlight(
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<Flight | null> {
    try {
      return await this.service.deleteFlight({
        where: params,
        select: {
          approvalComments: true,
          approvalStatus: true,
          approveStatus: true,
          arrivalAirport: true,
          arrivalTime: true,
          associatedPilot: true,
          createdAt: true,
          departureAirport: true,
          departureTime: true,
          flightNumber: true,
          id: true,
          remark: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/maintenanceRecords")
  @ApiNestedQuery(MaintenanceRecordFindManyArgs)
  async findMaintenanceRecords(
    @common.Req() request: Request,
    @common.Param() params: FlightWhereUniqueInput
  ): Promise<MaintenanceRecord[]> {
    const query = plainToClass(MaintenanceRecordFindManyArgs, request.query);
    const results = await this.service.findMaintenanceRecords(params.id, {
      ...query,
      select: {
        createdAt: true,

        flight: {
          select: {
            id: true,
          },
        },

        id: true,
        maintainer: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/maintenanceRecords")
  async connectMaintenanceRecords(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: MaintenanceRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceRecords: {
        connect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/maintenanceRecords")
  async updateMaintenanceRecords(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: MaintenanceRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceRecords: {
        set: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/maintenanceRecords")
  async disconnectMaintenanceRecords(
    @common.Param() params: FlightWhereUniqueInput,
    @common.Body() body: MaintenanceRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceRecords: {
        disconnect: body,
      },
    };
    await this.service.updateFlight({
      where: params,
      data,
      select: { id: true },
    });
  }
}
